# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blobby < Formula
  desc "A JSON blob analyser, breaking down by field to visualise blob makeup."
  homepage ""
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/RowMur/blobby/releases/download/v0.0.4/blobby_Darwin_x86_64.tar.gz"
      sha256 "455abb60f2adc6bd59028c8f2b7bec9a7288ec11cc78c61f2f2d06d8f9373ab2"

      def install
        bin.install "blobby"
      end
    end
    on_arm do
      url "https://github.com/RowMur/blobby/releases/download/v0.0.4/blobby_Darwin_arm64.tar.gz"
      sha256 "2b8cd48c782a19aad33d6a5afb064ba8333bf289cfb9b60eb071627efa56d35b"

      def install
        bin.install "blobby"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/RowMur/blobby/releases/download/v0.0.4/blobby_Linux_x86_64.tar.gz"
        sha256 "de5bf96232455090ccb768493e54ad273080c5cf9a10a42138c905c50b68776b"

        def install
          bin.install "blobby"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/RowMur/blobby/releases/download/v0.0.4/blobby_Linux_arm64.tar.gz"
        sha256 "576fb7953dfa0547cea458ca3b0461b4e2c099fad1cb215e23079199a736e0d1"

        def install
          bin.install "blobby"
        end
      end
    end
  end
end
